### PR TITLE
ActiveRecord 5.0.1 Support

### PR DESCRIPTION
**Pull request by boazy**

### CODE REVIEW

**Comment by boazy** [comment]
@ronen Do you want to review this change?

**Comment by ronen** [comment]
@boazy thanks for getting it working!  I pushed another way of resolving the faux nested method warnings -- just make it a regular method :)

Also, I wonder about whether to bother with the 5.0.0 backwards compatibility.  We could just change the gemspec to require `"~>5.0"` and `">= 5.0.1"`.  for anyone using 5.0.0, bundle update would continue resolve to the current release of schema_plus_pg_indexes, and for anybody who upgraded to 5.0.1 bundle update would would get the new release.    What do you think?

**Comment by boazy** [comment]
@ronen
Thanks. Sibling method is a better option. I thought we needed to capture a local variable for some reason, so I went with a lambda, but I was wrong.

Is it safe to assume that everyone can easily upgrade from 5.0.0 to 5.0.1 and we don't need any backward compatibility for minor versions here?
Technically speaking, there shouldn't be any breaking changes moving from 5.0.0 to 5.0.1, but as we saw in this case, things can break for gems that rely on ActiveRecord internals. Since users of schema_plus_pg_indexes are very likely to be also using other SchemaPlus gems, they can run into a situation where one gem supports 5.0.1 and another one supports only 5.0.0. We should obviously fix the other gem then, but they would have to wait until we fix it.

I'm still not sure whether it's worth supporting 5.0.0 though.

**Comment by ronen** [comment]
> Technically speaking, there shouldn't be any breaking changes moving from 5.0.0 to 5.0.1, but as we saw in this case, things can break for gems that rely on ActiveRecord internals.

True, but as long we update `schema_plus_pg_indexes.gemspec` to require AR >= 5.0.1 for this upcoming release, then anybody on 5.0.0 will continue to get the old release, which will continue to work for them...

> I'm still not sure whether it's worth supporting 5.0.0 though.

...so the question is really whether we want to support *both* 5.0.0 and 5.0.1 simultaneously in a single release.   And I'm leaning away from supporting both simultaneously.  Doesn't seem worth keeping the extra code around with the requisite extra maintenance & testing & general clutter.

**Comment by boazy** [comment]
> True, but as long we update schema_plus_pg_indexes.gemspec to require AR >= 5.0.1 for this upcoming release, then anybody on 5.0.0 will continue to get the old release, which will continue to work for them...

Yes. I guess I'm worried too much about a perfect storm of a user who wants a putative bugfix in a future schema_plus_pg_indexes version, but still needs to stick with AR 5.0.0 for some reason (perhaps because another SchemaPlus gem). This is probably not worth the maintenance effort of supporting both versions, so I'll modify my PR.

**Comment by boazy** [comment]
@ronen OK, done. I want to squash all commits before merging (we don't need to keep all the back and forth), so please tell me after you finish reviewing :)

**Pull request merged**
