### PR TITLE
[Reopened] Support for Active Record 5

### PR DESCRIPTION
**Pull request by boazy**
Everything is ready, except for doc updates.

### CODE REVIEW

**Comment by zharikovpro** [comment]
I'm already using gem from this branch and can confirm that it works at first glance (using it with unique indexes). Can I help with something else to expedite PR merge?

**Comment by ronen** [comment]
@zharikovpro your testimonial was a good help :)

Version 0.2.0 is released

**Comment by ronen** [comment]
Oh dear.  Since a few days ago and today it seems that AR 5.0.1 must have been released, and this now fails.  For now I guess continue to use AR 5.0.0 until somebody can fix this...

**Comment by ronen** [comment]
I poked around a tiny bit.  The problem is that the calling sequence for `:add_index_sort_order` has changed, with the arguments refactored.  See rails/rails@2620a23929752f53744364d604cb43c1627be00d -- Hopefully it'll be fairly simple to conform the code at [middleware/postgresql/sql.rb#L58](https://github.com/SchemaPlus/schema_plus_pg_indexes/blob/master/lib/schema_plus_pg_indexes/middleware/postgresql/sql.rb#L58)
that builds the arguments.

Unfortunately I don't have the time dive into it right now.  Anybody else...?

**Comment by boazy** [comment]
I'll took a look at that in the next opportunity I get. :)

**Pull request merged**
