### PR TITLE
add rails 5.2 support

### PR DESCRIPTION
**Pull request by urkle**

### CODE REVIEW

**Comment by lowjoel** [comment]
I'll try to review these, let me know when it's ready for review.

**Comment by urkle** [comment]
@lowjoel this one passes locally and will pass  once a new schema_plus_indexes gem is released.

Now this one does have that "nefarious" Gem::Version check in the main ruby entrypoint file. Mainly because this whole gem is going to become deprecated for 5.2 and not supported after that.

**Comment by lowjoel** [comment]
No, this makes sense. If we're going to remove a component gem, we should just warn noisily.

I can't remember offhand if everyone's migrations will be run, and I'm just afraid that after upgrading migrations will stop working after Rails 5.2, since I don't imagine migrations to be a particularly well-tested code path.

**Review by lowjoel — APPROVED** [review]

**Comment by lowjoel** [comment]
If you can think of a better solution than just telling people to update migrations, I think we should do it. But such a solution eludes me at the moment...

**Comment by urkle** [comment]
@lowjoel and the way this is coded right now those migrations will still work, and it will yell noisily. :)

I'm actually going to take a peek at paperclip as that one YELLS noisily on install somehow when things change.. And we could have a warning on startup everytime the gem is loaded too.

**Pull request merged**
